### ISSUE TITLE
`npm publish` fails for a new package

### ISSUE THREAD

**Issue by bajtos** [mbrevoort/node-reggie#11]
When publishing a new package using `npm publish` and `publishConfig`, the command fails:

```
$ npm publish
npm http PUT http://localhost:8080/private-module
npm http 200 http://localhost:8080/private-module
npm http GET http://localhost:8080/private-module
npm http 404 http://localhost:8080/private-module
npm ERR! 404 'private-module' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
```

Once the first version of the package is published via the `reggie` client, subsequent `npm publish` works correctly.

**Comment by durango** [comment]
Was this fixed by the recent merge for .13? Judging from the spec tests it seems so, but I could be wrong? Also, how do you guys recommend starting reggie under a daemon? Forever, naught, p2, or just plain ol' &?

**Comment by bajtos** [comment]
> Was this fixed by the recent merge for .13? Judging from the spec tests it seems so, but I could be wrong? 

Yes, it was fixed by that PR. I forgot to close the issue, thank you for pointing it out.

> Also, how do you guys recommend starting reggie under a daemon? Forever, naught, p2, or just plain ol' &?

I am afraid I don't have any recommendation to offer here.
