### ISSUE TITLE
Fall back to npm registry on unknown packages

### ISSUE THREAD

**Issue by spmason** [mbrevoort/node-reggie#14]
So you could have Reggie host your private packages and fall back to the main repo for public stuff.

It could even "cache" packages locally itself, to speed things up

Is this something reggie would/should ever do?

**Comment by durango** [comment]
The cache, if it were to be done, should be configurable (I specifically would never need cache), but the fallback to the main repo would be incredibly awesome :+1:

**Comment by bajtos** [comment]
I don't think this feature fits into Reggie.
1. The current plan is to modify npm client to support multiple registries. This way the logic for merging package info from multiple registries can remain in a single place - in the npm client. The work on this feature has already begun.
2. Remember the Unix way, which is a way of Node.js too? Have many small components, each component doing one thing only and doing it well? I'd prefer to have a caching npm proxy implemented as a standalone service.

BTW there are already projects implementing both private registry and npm cache: [shadow-npm](https://github.com/substack/shadow-npm), [nopar](https://github.com/afbobak/nopar) and probably one or two more that I couldn't quickly google out.

**Comment by spmason** [comment]
That was the response I thought I'd get, to be honest, and that's fine by me really

One thing, where's your source that someone is working on multiple registries? From what I can find there hasn't been movement on it for a while (https://github.com/isaacs/npm/pull/100, https://github.com/isaacs/npm/issues/1401, https://github.com/isaacs/npm/pull/3093)

**Comment by bajtos** [comment]
> One thing, where's your source that someone is working on multiple registries? From what I can find there hasn't been movement on it for a while (isaacs/npm#100, isaacs/npm#1401, isaacs/npm#3093)

Well, it's me who is working on multiple registries. I guess I should have announced it sooner. Anyway, I commented on isaacs/npm#1401 so that people know there is some progress being made.

**Comment by bajtos** [comment]
@spmason one of the other projects I could not remember is [sinopia](https://github.com/rlidwka/sinopia). The guy seems to make a steady progress. There is also a list of other alternative solutions at the end of project's [README](https://github.com/rlidwka/sinopia#similar-existing-things).
