### ISSUE TITLE
Add travis-ci build

### ISSUE THREAD

**Issue by bajtos** [mbrevoort/node-reggie#16]
Hi @mbrevoort,

Could you please enable travis-ci hook for this repository? I'd like to setup a CI build server for Reggie and add badge to README.md. See steps 1 & 2 in [Travis CI: Getting Started](http://about.travis-ci.org/docs/user/getting-started/#Step-one%3A-Sign-in).

I can do the rest (add `.travis.yml`, etc.) to get CI up and running.

**Comment by mbrevoort** [comment]
Hey, yes, I just enabled travis on the reggie repo.

Also, I liked your contributor rules. Do you want to add a section at the
end of the README with the same details?

Thanks!
Mike

**Comment by bajtos** [comment]
> I just enabled travis on the reggie repo.

Excellent! The build is failing now, I'll investigate and fix the problem.

> Also, I liked your contributor rules. Do you want to add a section at the
> end of the README with the same details?

Do you mean the 50/72 rule for commit messages? Here is what I did for Node Inspector, perhaps I can copy the content to Reggie?
- https://github.com/node-inspector/node-inspector#contributing-code
- https://github.com/node-inspector/node-inspector/wiki/Contributing

I am also thinking about adding .jshintrc and configuring travis to run jshint as a pre-build script. This should keep the coding style clean and consistent. Any objections? Here is my preferred jshint config: [.jshintrc](https://github.com/strongloop/strong-caching-http-client/blob/master/.jshintrc)

**Comment by bajtos** [comment]
Contributor rules were added in d5f3013. I am closing the issue.
