### ISSUE TITLE
Configure the host to listen on

### ISSUE THREAD

**Issue by akoenig** [mbrevoort/node-reggie#31]
Awesome project! I also planned to implement something like reggie in order to manage our modules. So thanks for building this. It's great!

Do you think that it is a good idea to provide a start argument to configure the host. There are some cases where I want to run the reggie-server on my local machine and therefore don't want to expose it to the whole network.

Something like:

-s, --source Which kind of connections shall Reggie accept? [default: '0.0.0.0']

What do you think?

**Comment by bajtos** [comment]
Released in v0.2.0.
