### ISSUE TITLE
Get packages through public npm

### ISSUE THREAD

**Issue by RobertPrediger** [mbrevoort/node-reggie#46]
Let's assume, you are using `reggie` as private registry.

Great would be, if `reggie` would search for all not found modules in the global registry and pipe it through.

Private modules will be delivered via `reggie` and global modules will be found as well.
In this scenario, we could use the private registry in package.json and are independent from having multiple registries and we'd be able to install every module via `npm install <module>`, private or global.

**Comment by leftieFriele** [comment]
I think it's better if Reggie just does one thing - host private modules. 
You can use modules such as Kappa in front of Reggie to achieve what you describe.

**Comment by bajtos** [comment]
:+1: for keeping reggie doing one thing only.

Besides the options mentioned by @leftieFriele , you can also try [Sinopia](https://github.com/rlidwka/sinopia).
