### ISSUE TITLE
Why doesn't Kappa + Reggie work?

### ISSUE THREAD

**Issue by parris** [mbrevoort/node-reggie#49]
I'm trying to put both the npm registry (with nginx proxy cache) and reggie behind kappa. Kappa should try to get a package from the npm registry and proxy cache then fail and fall back to reggie. That doesn't currently happen.

If someone gets to this before me then awesome. Otherwise, I'll check it out myself.

By the way this is an awesome package! We are using it here at Eventbrite. Also putting it in my presentation for HTML5 dev conf in SF. Let me know if you guys need any help.

Thanks!

**Comment by leftieFriele** [comment]
I used kappa in front of reggie, but we had reggie as the first item in the list. Then kappa fell back if the module didn't exist in our local repo which only had the modules which should remain private.

however we since moved away from reggie after advice from the module owners that reggie wasn't being updated anymore.

**Comment by parris** [comment]
@leftieFriele that makes sense. Also, that's a bummer, why did they stop updating? Not everyone wants to be a couchdb sysadmin.

Also what are you using now instead (if anything)?

**Comment by parris** [comment]
I just read, the pull request. Sinopia looks cool. I'll ride out node-reggie for a little while. Hopefully, breaking changes don't come to npm in the next year. Although I've heard private npm stuff is supposed to be easier and built in, in the future...

**Comment by leftieFriele** [comment]
We've moved to Sinopia without any problems. Using it you don't have to use
Kappa either as it has support for querying multiple repos and cache
artifacts.
