### ISSUE TITLE
question: creating private regsitry with the test folder from npm modules

### ISSUE THREAD

**Issue by smartmouse** [mbrevoort/node-reggie#53]
Hi Thanks for writing this node-module, I love it, very easy to use.
I have a question - some node modules comes with a test folder when it is not part  of the npm install.
What I did is to git clone the node module A on a machine , then it has the test folder.
and then I publish the node-modules to my own private registry. using reggie.

Now if I do a npm install  http://myregistryURL:8080/ A/version

The test folder did not  get pulled  of course
Is there a way to have the test  folder included when we do npm install from my privateRegistry?

Thanks for your help.

**Comment by bajtos** [comment]
Check your `.gitignore` and `.npmignore` files and make sure `test` is not listed there. AFAIK, reggies calls `npm` to package your module. You can run `npm pack` to see what will be included in your package.
